### ISSUE TITLE
Multiple issues during fresh install of pivpn on RASPBIAN STRETCH LITE

### ISSUE THREAD

**Issue by Pi-DPiper** [pivpn/pivpn#408]
Hello,

I've been meaning to setup a VPN for a while and wanting to use a Pi for this.
Today I spent a good few hours trying to get pivpn to work following this guide:

- https://www.youtube.com/watch?v=BwLBq1j1sw

I've had issues when making use of:

- RASPBIAN STRETCH LITE - v4.9

- Pi model 3

The list of issues so far are:

1. On initially imaging over Raspbian, running a sudo apt-get update fails with time outs or messages that server cannot be found. I partially fixed this disabling IPv6 via one of the config files, but think there may still be an issue with one of the mirrors. I know my home connection is working fine from testing.

2.  On initially running 'curl -L https://install.pivpn.io | bash' I found that at least once the installer would stop half way with no warning and just leave the blue status screen and go back to the terminal. I did get this to run after re-imaging my Pi and trying a 2nd time.

3. When the install did run, it did not come up asking me what DNS I wanted to use like in the video guide I followed. I needed to enter this manually editing a config.

4. When generating a new user to use the VPN, the system complained that the path/home folder was invalid and did not exist. I verified this, and attempted to fix by manually making the directory.

With all of the above done, I then attempted to use the .ovpn file on both my android phone and my windows computer. Both of these failed, suggesting something was wrong in the file.

One thing to note, is during setup I chose the 1024 key size to keep things/testing simple.

I see some other people have similar issues, and am at a bit of a loss as to what to do next.
This is my first time trying to deploy this setup, and it seems I'm getting issues at every step.

Can anyone advise on this, is there a known working combination of pivpn and the underlying OS I can use? I don't mind tinkering, but this initial test has gone from fun to frustrating quite quickly.

Alternatively, is there an alternate recommended VPN solution for the Pi?
I've checked into deploying OpenVPN manually using ubuntu or similar...but the steps seem very complex with many pre-requites compared.

Many thanks for any input you can offer.

**Comment by cfcolaco** [comment]
something smells terribly wrong here!! 

I am somehow reluctant to youtube tutorials around there! please use the official information from raspbian and from us here.
 
Here you can find the Rraspbian stretch and all the information you need to properly Image your sdcard with it:  

https://www.raspberrypi.org/downloads/raspbian/ 
https://www.raspberrypi.org/documentation/installation/installing-images/README.md

even having pivpn doing so ... run sudo apt-get update && sudo apt-get upgrade before starting the script 

The script is made in a way that anyone without much knowledge can make OpenVPN work. 
So Please read carefully all the information we provide here! 
We have the README right in the start page of this repo, we have the wiki and faqs also inside this repo! 

Regarding your questions, OpenVPN is indeed the best way you have to have your own VPN up and running, setting it up manually is not something quite hard to do, however, requires you to have a bit more dexterity with a Linux system. 

Please Re image your sdcard with raspbian stretch, follow this easy steps I mention here, and info we provide! if that doesn't work, please say something so I can try to help you out!

**Comment by fiz1962** [comment]
I've used PiVPN on several versions of Pi over a couple years.  I just tried removing (pivpn uninstall) and reinstalling in a Pi3 and have similar issues.

(1) /etc/pivpn/INSTALL_USER is not created leading to a failed copy of the opvn file to "/home//ovpns"
(2) If I manually create INSTALL_USER the /home/pi/ovpns folder has to be manually created
(3) Doing (1) and (2) will copy the file but everything normally in the ovpn file preceeding "<ca>" is missing.  An example of this missing info is pasted below from another opvn file
(4) I see the following errors (below) when running the script with debug option
================
Using configuration from /etc/openvpn/easy-rsa/openssl-1.0.cnf
Can't open /etc/openvpn/easy-rsa/pki/index.txt.attr for reading, No such file or directory
1995793824:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:74:fopen('/etc/openvpn/easy-rsa/pki/index.txt.attr','r')
1995793824:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:81:
================
client
dev tun
proto udp
remote xx.xx.xx.xx 1194
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 1
redirect-gateway def1
<ca>
...

**Comment by CrackerStealth** [comment]
There appears to be an issue with the installer creating the config file in the /etc/pivpn/ with all the variables required to run the pivpn command.

I was able to work around the issue in my setup by uninstalling `pivpn uninstall` and then installing the software with this command `curl -L https://install.pivpn.io | sudo bash`.

Escalating the entire installer to root gets around the permissions issue of the configuration file unable to be written where it should be.

**Comment by salvatoro** [comment]
Got the exact same problem as  Pi-DPiper and fix1962 but I am using Raspbian stretch nov 2017 (4.9.59-v7+). I had to blacklist ipv6 to be able to network since my ISP is not fully ipv6 capable.

pivpn installation stopped at DH parameters, never selected the DNS server. The result is that even if I grab the files from /etc/openvpn/easyrsa/pki, the client warns that there is no address, tun or interface.

files tried to be copied in /home//ovpns. Install_user variable never created properly. 

CrackerStealth solution | sudo bash did not work neither.

Thanks for your help

**Comment by fiz1962** [comment]
I ended up searching and found a couple branches of PiVPN.  I may have ended up using OpenVPN-Setup from https://github.com/StarshipEngineer/OpenVPN-Setup but it may have been another.

**Comment by salvatoro** [comment]
Thanks for the info. As far as I know, that branch is using easy-rsa v2. I had an issue with the script not creating the certification authority but it isn't a major problem and I'm going to try editing the script. I am also going to try pivpn with easy-rsa v2

**Comment by cfcolaco** [comment]
@salvatoro hmm ...seems this is solved then? 

please let me know if this needs to be reopen!

**Comment by salvatoro** [comment]
Well it is not solved, i did not manage to set up the server using pivpn script, i used another one from starship engineer that i also had to tune. After i got it working with easy rsa 2 i migrated to easy rsa 3.

**Comment by Dilepa** [comment]
Cannot install pivpn on pi 3B+ running stretch.


Using configuration from /etc/openvpn/easy-rsa/openssl-1.0.cnf
Can't open /etc/openvpn/easy-rsa/pki/index.txt.attr for reading, No such file or directory
1995666848:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:74:fopen('/etc/openvpn/easy-rsa/pki/index.txt.attr','r')
1995666848:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:81:
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'server_CHjXYBkoU6WV9WRc'
Certificate is to be certified until Apr  1 03:59:03 2028 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated

I am getting the same errors ....

Also not able to get to the dns servers and remote hostnames to set up.

pivpn -a also runs but cannot create the .ovpn files in pi user.
