### ISSUE TITLE
comp-lzo is no longer valid

### ISSUE THREAD

**Issue by lookfirst** [pivpn/pivpn#473]
<img width="617" alt="tunnelblick 2018-02-22 10-46-19" src="https://user-images.githubusercontent.com/85355/36519414-f1a29026-17bd-11e8-86fd-c00f5e0f29ad.png">

**Comment by cfcolaco** [comment]
This is solved with pr #471 

Discussion regarding this being tracked at #473

**Comment by teake** [comment]
Sorry to reopen this, but I I just re-installed PiVPN on my Raspberry Pi 3 and am still getting the above warning. 

I double-checked the discussion in #474 and realized that I didn't get the `Version 2.4 improvements` whiptail dialog during install. There's a conditional around that dialog that prevents it from showing in Raspbian: 

https://github.com/pivpn/pivpn/blob/33e7ef0c9191c86f74d6b7bc06371350d49e3af9/auto_install/install.sh#L839 

What's the recommended way to get 2.4 improvements in Raspbian?

**Comment by teake** [comment]
Ok, nevermind, I'm on Raspbian Jessie and my OpenVPN version is 2.3.4. Looks like I'll be updating to Raspbian Stretch (see also #280).
