### ISSUE TITLE
Installation skipped "Public IP or DNS" question

### ISSUE THREAD

**Issue by frdrrhr** [pivpn/pivpn#566]
## Issue

After posting here (https://github.com/pivpn/pivpn/issues/475) I tried a new round of installing pivpn on a complete fresh DietPi (v6.12).
The installation finished after the "Version 2.4 improvements" window and did not show the "Public IP or DNS" question.

## Have you searched for similar issues and solutions? 
yes, for example: https://github.com/pivpn/pivpn/issues/475

## Console output of `curl -L install.pivpn.io | bash`
```
[  OK  ] DietPi-Software | G_AGI: lsb-release
--2018-07-23 17:23:59--  https://install.pivpn.io/
Resolving install.pivpn.io (install.pivpn.io)... 71.19.155.138
Connecting to install.pivpn.io (install.pivpn.io)|71.19.155.138|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh [following]
--2018-07-23 17:24:00--  https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.112.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 54741 (53K) [text/plain]
Saving to: ‘pivpn_install.sh’

2018-07-23 17:24:00 (1.56 MB/s) - ‘pivpn_install.sh’ saved [54741/54741]

:::
::: You are root.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::
::: Setting IP to 192.168.178.25.  You may need to restart after the install is complete.
:::
::: Using User: dietpi
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn... done!
:::
::: Stopping OpenVPN service... done.
:::   
::: Installing scripts to /opt/pivpn... done.
::: Using protocol: udp
::: Building CA...
Generating a 2048 bit RSA private key
................................................................................................+++
..............+++
writing new private key to '/etc/openvpn/easy-rsa/pki/private/ca.key....'
-----

::: CA Complete.

Note: using Easy-RSA configuration from: ./vars
rand: Use -help for summary.
Generating a 2048 bit RSA private key
.......................................................................................................+++
...........................+++
writing new private key to '/etc/openvpn/easy-rsa/pki/private/server_P5sUSxi2RR1vE8Z9.key....'
-----
Using configuration from /etc/openvpn/easy-rsa/openssl-1.0.cnf
Can't open /etc/openvpn/easy-rsa/pki/index.txt.attr for reading, No such file or directory
3070042112:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:74:fopen('/etc/openvpn/easy-rsa/pki/index.txt.attr','r')
3070042112:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:81:
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'server_P5sUSxi2RR1vE8Z9'
Certificate is to be certified until Jul 20 16:34:07 2028 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated

Note: using Easy-RSA configuration from: ./vars
Using configuration from /etc/openvpn/easy-rsa/openssl-1.0.cnf

An updated CRL has been created.
CRL file: /etc/openvpn/easy-rsa/pki/crl.pem

net.ipv4.ip_forward = 1
run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save
run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save
ip6tables-save v1.6.0: Cannot initialize: Address family not supported by protocol

run-parts: /usr/share/netfilter-persistent/plugins.d/25-ip6tables exited with return code 1
::: Install Complete...
::: Restarting services...
Synchronizing state of openvpn.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable openvpn
::: done.
:::
::: Installation Complete!
::: Now run 'pivpn add' to create an ovpn profile for each of your devices.
::: Run 'pivpn help' to see what else you can do!
::: It is strongly recommended you reboot after installation.
:::
::: The install log is located at: /etc/pivpn/install.log
[ SUB2 ] DietPi-Services > stop
[  OK  ] DietPi-Services | stop : cron
[  OK  ] DietPi-Services | stop : fail2ban
[ SUB1 ] DietPi-Software > Optimize and configure software
[ INFO ] DietPi-Software | Applying DietPi optimizations and configurations for RPi B (armv6l), please wait...

[ SUB2 ] DietPi-Services > dietpi_controlled
[  OK  ] DietPi-Services | dietpi_controlled : fail2ban
[  OK  ] DietPi-Services | dietpi_controlled : cron
[  OK  ] DietPi-Survey | Connection test: dietpi.com
[ SUB1 ] DietPi-Software > Installation completed
[  OK  ] DietPi-Software | The system will now reboot. 
 This completes the DietPi-Software installation.

**Comment by natanaelxp** [comment]
Same problem here, using raspian

**Comment by supersook** [comment]
Same issue here using a fresh Raspbian install.
When adding a new user, same issue as #557.
The Default.txt doesn't seem to be present or in the location where the scripts get executed.

Here's the output of the install.log:
```
:::
::: Stopping OpenVPN service... done.
:::
::: Installing scripts to /opt/pivpn... done.
::: Using protocol: udp
::: Building CA...

::: CA Complete.

Note: using Easy-RSA configuration from: ./vars

Note: using Easy-RSA configuration from: ./vars

An updated CRL has been created.
CRL file: /etc/openvpn/easy-rsa/pki/crl.pem

net.ipv4.ip_forward = 1
```

**Comment by honikos** [comment]
same for me on my PI 2 B:

PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian

**Comment by LaBoss** [comment]
same for me on my PI 2 b on raspbian 9 no dns or public IP option and no default txt

**Comment by Iloller** [comment]
Same for me on PI 3b+ with raspbian lite. no option for public IP/dns, also no default.txt file and when creating a ovpn file the directory is /home//ovpns while I selected a profile to use.

**Comment by AdvancedFollower** [comment]
Same issue here on DietPi on my Pi 3B+.
Default.txt and INSTALL_USER are missing and I never got the option to set a public DNS/IP during the setup.

**Comment by orazioedoardo** [comment]
I think I've fixed the issue on dietpi, it was related to apt not using https. You need to change [this if block](https://github.com/pivpn/pivpn/pull/597/files#diff-299d9b30c952310aace4aba77c698874L469) according to the commit. It worked for me on a fresh install of dietpi.

**Comment by Iloller** [comment]
Ibam using normal rasbian lite, not diet pi. I got vpn working with another script installer  
https://github.com/angristan/openvpn-install/blob/openvpn-2.4-update/README.md

**Comment by bezin** [comment]
Same issue for me here. The fix proposed by @orazioedoardo did not fix it for my. Any ideas?

**Comment by orazioedoardo** [comment]
Well, actually it wan’t a fix. It would just show what commands are being run so we could see what it skipped.

**Comment by bezin** [comment]
Oh ok, thanks for clarification. I am on Raspbian Stretch

**Comment by orazioedoardo** [comment]
So, can you try this?

> Don't know about raspbian, however, you can help adding these two lines: set -v and set -x to the top of the script (right after #!/bin/bash) before running. Having the full report would be nice however you should purge it from personal information.

**Comment by bezin** [comment]
Will try in a moment.

**Comment by orazioedoardo** [comment]
Same as him then: https://github.com/pivpn/pivpn/issues/521#issuecomment-420975343
So there is something wrong when piping from bash but it’s working for me so I can find out why.

**Comment by 4s3ti** [comment]
closing this as no further activity and seems it got somehow fixed. 
If it happens again feel free to reopen for investigation.
