### ISSUE TITLE
[BUG] PiVPN Can't connect via Android Client (Testing Branch) - Not Listening Error

### ISSUE THREAD

**Issue by spectrumcomputing** [pivpn/pivpn#901]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
Working from clean installation (Testing Branch) of Raspbian Buster Lite on Raspberry Pi 3. Install goes OK, I choose OpenVPN. Able to add client. Import the key into Android OpenVPN client and it can't connect. I'm using NoIP

**To Reproduce**
1. Install testing branch on clean installation
2. Add client
3. Copy client to android phone and import into OpenVPN
4. Can't connect

**Smartphone (please complete the following information):**
 - VPN Protocol UDP
 - Device: Moto G6
 - OS: Android
 - 8

**Additional context**
When I run ```pivpn debug``` I get the following message:

```
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [ERR] OpenVPN is not listening, try to restart now? [Y/n]
```

If I choose 'Y' I get this:
```
pi@raspberrypi:~ $ pivpn debug
::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit a9f5e7346fa596f021bcf8a043b749dc14b86986
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Tue Dec 31 12:28:26 2019 +0100

    Revert to more portable commands
=============================================
::::        Installation settings        ::::
=============================================
::::    setupVars file shown below       ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
IPv4addr=192.168.1.215
IPv4gw=192.168.1.254
install_user=pi
install_home=/home/pi
VPN=openvpn
pivpnPROTO=udp
pivpnPORT=1194
pivpnDNS1=1.1.1.1
pivpnDNS2=1.0.0.1
pivpnSEARCHDOMAIN=
pivpnHOST=REDACTED
pivpnENCRYPT=2048
DOWNLOAD_DH_PARAM=0
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
UNATTUPG=1
TO_INSTALL=(git dnsutils iptables-persistent openvpn grepcidr expect unattended-upgrades)
HELP_SHOWN=1
=============================================
::::  Server configuration shown below   ::::
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/raspberrypi_0fd30448-bae4-4a6f-8d6f-797f491f8222.crt
key /etc/openvpn/easy-rsa/pki/private/raspberrypi_0fd30448-bae4-4a6f-8d6f-797f491f8222.key
dh /etc/openvpn/easy-rsa/pki/dh2048.pem
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 1.1.1.1"
push "dhcp-option DNS 1.0.0.1"
# Prevent DNS leaks on Windows
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 15 120
remote-cert-tls client
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
user openvpn
group openvpn
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device.
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
client
dev tun
proto udp
remote REDACTED 1194
resolv-retry infinite
nobind
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name raspberrypi_0fd30448-bae4-4a6f-8d6f-797f491f8222 name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
::::    Recursive list of files in       ::::
::: /etc/openvpn/easy-rsa/pki shows below :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
dh.pem
extensions.temp
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
openssl-easyrsa.cnf
OpenVPN-MotoG6.ovpn
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
OpenVPN-MotoG6.crt
raspberrypi_0fd30448-bae4-4a6f-8d6f-797f491f8222.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
OpenVPN-MotoG6.key
raspberrypi_0fd30448-bae4-4a6f-8d6f-797f491f8222.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [ERR] OpenVPN is not listening, try to restart now? [Y/n] Y
Done
[INFO] Run pivpn -d again to see if we detect issues
=============================================
::::      Snippet of the server log      ::::
Jan  2 17:13:31 raspberrypi ovpn-server[1716]: Options error: Please correct these errors.
Jan  2 17:13:31 raspberrypi ovpn-server[1716]: Use --help for more information.
Jan  2 17:13:37 raspberrypi ovpn-server[1719]: Options error: --dh fails with '/etc/openvpn/easy-rsa/pki/dh2048.pem': No such file or directory (errno=2)
Jan  2 17:13:37 raspberrypi ovpn-server[1719]: Options error: Please correct these errors.
Jan  2 17:13:37 raspberrypi ovpn-server[1719]: Use --help for more information.
Jan  2 17:13:42 raspberrypi ovpn-server[1758]: Options error: --dh fails with '/etc/openvpn/easy-rsa/pki/dh2048.pem': No such file or directory (errno=2)
Jan  2 17:13:42 raspberrypi ovpn-server[1758]: Options error: Please correct these errors.
Jan  2 17:13:42 raspberrypi ovpn-server[1758]: Use --help for more information.
Jan  2 17:13:47 raspberrypi ovpn-server[1770]: Options error: --dh fails with '/etc/openvpn/easy-rsa/pki/dh2048.pem': No such file or directory (errno=2)
Jan  2 17:13:47 raspberrypi ovpn-server[1770]: Options error: Please correct these errors.
Jan  2 17:13:47 raspberrypi ovpn-server[1770]: Use --help for more information.
Jan  2 17:13:52 raspberrypi ovpn-server[1773]: Options error: --dh fails with '/etc/openvpn/easy-rsa/pki/dh2048.pem': No such file or directory (errno=2)
Jan  2 17:13:52 raspberrypi ovpn-server[1773]: Options error: Please correct these errors.
Jan  2 17:13:52 raspberrypi ovpn-server[1773]: Use --help for more information.
Jan  2 17:13:58 raspberrypi ovpn-server[1777]: Options error: --dh fails with '/etc/openvpn/easy-rsa/pki/dh2048.pem': No such file or directory (errno=2)
Jan  2 17:13:58 raspberrypi ovpn-server[1777]: Options error: Please correct these errors.
Jan  2 17:13:58 raspberrypi ovpn-server[1777]: Use --help for more information.
Jan  2 17:14:03 raspberrypi ovpn-server[1803]: Options error: --dh fails with '/etc/openvpn/easy-rsa/pki/dh2048.pem': No such file or directory (errno=2)
Jan  2 17:14:03 raspberrypi ovpn-server[1803]: Options error: Please correct these errors.
Jan  2 17:14:03 raspberrypi ovpn-server[1803]: Use --help for more information.
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::
pi@raspberrypi:~ $
```

This is the full output:

```
pi@raspberrypi:~ $ pivpn debug
::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit a9f5e7346fa596f021bcf8a043b749dc14b86986
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Tue Dec 31 12:28:26 2019 +0100

    Revert to more portable commands
=============================================
::::        Installation settings        ::::
=============================================
::::    setupVars file shown below       ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
IPv4addr=192.168.1.215
IPv4gw=192.168.1.254
install_user=pi
install_home=/home/pi
VPN=openvpn
pivpnPROTO=udp
pivpnPORT=1194
pivpnDNS1=1.1.1.1
pivpnDNS2=1.0.0.1
pivpnSEARCHDOMAIN=
pivpnHOST=REDACTED
pivpnENCRYPT=2048
DOWNLOAD_DH_PARAM=0
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
UNATTUPG=1
TO_INSTALL=(git dnsutils iptables-persistent openvpn grepcidr expect unattended-upgrades)
HELP_SHOWN=1
=============================================
::::  Server configuration shown below   ::::
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/raspberrypi_0fd30448-bae4-4a6f-8d6f-797f491f8222.crt
key /etc/openvpn/easy-rsa/pki/private/raspberrypi_0fd30448-bae4-4a6f-8d6f-797f491f8222.key
dh /etc/openvpn/easy-rsa/pki/dh2048.pem
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 1.1.1.1"
push "dhcp-option DNS 1.0.0.1"
# Prevent DNS leaks on Windows
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 15 120
remote-cert-tls client
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
user openvpn
group openvpn
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device.
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
client
dev tun
proto udp
remote REDACTED 1194
resolv-retry infinite
nobind
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name raspberrypi_0fd30448-bae4-4a6f-8d6f-797f491f8222 name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
::::    Recursive list of files in       ::::
::: /etc/openvpn/easy-rsa/pki shows below :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
dh.pem
extensions.temp
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
openssl-easyrsa.cnf
OpenVPN-MotoG6.ovpn
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
OpenVPN-MotoG6.crt
raspberrypi_0fd30448-bae4-4a6f-8d6f-797f491f8222.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
OpenVPN-MotoG6.key
raspberrypi_0fd30448-bae4-4a6f-8d6f-797f491f8222.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [ERR] OpenVPN is not listening, try to restart now? [Y/n]
```

**Comment by orazioedoardo** [comment]
Solved here, thanks: https://github.com/pivpn/pivpn/commit/ef6e84419e6e7e0e10937c42c0ff8210d42a4a3d

You can fix your installation with:
```
sudo -s
cd /etc/openvpn/easy-rsa/pki/
mv dh.pem dh2048.pem
systemctl restart openvpn
exit
```

**Comment by spectrumcomputing** [comment]
Thanks for replying so quickly.  That seems to have fixed the debug, but it still won't connect.  I will try switching off everything and rebooting, and will report back.  Thank you.

```pi@raspberrypi:~ $ pivpn debug
::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit a9f5e7346fa596f021bcf8a043b749dc14b86986
Author: Orazio <orazioedoardo@users.noreply.github.com>
Date:   Tue Dec 31 12:28:26 2019 +0100

    Revert to more portable commands
=============================================
::::        Installation settings        ::::
=============================================
::::    setupVars file shown below       ::::
PLAT=Raspbian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
IPv4addr=192.168.1.215
IPv4gw=192.168.1.254
install_user=pi
install_home=/home/pi
VPN=openvpn
pivpnPROTO=udp
pivpnPORT=1194
pivpnDNS1=1.1.1.1
pivpnDNS2=1.0.0.1
pivpnSEARCHDOMAIN=
pivpnHOST=REDACTED
pivpnENCRYPT=2048
DOWNLOAD_DH_PARAM=0
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
UNATTUPG=1
TO_INSTALL=(git dnsutils iptables-persistent openvpn grepcidr expect unattended-upgrades)
HELP_SHOWN=1
=============================================
::::  Server configuration shown below   ::::
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/raspberrypi_0fd30448-bae4-4a6f-8d6f-797f491f8222.crt
key /etc/openvpn/easy-rsa/pki/private/raspberrypi_0fd30448-bae4-4a6f-8d6f-797f491f8222.key
dh /etc/openvpn/easy-rsa/pki/dh2048.pem
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 1.1.1.1"
push "dhcp-option DNS 1.0.0.1"
# Prevent DNS leaks on Windows
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 15 120
remote-cert-tls client
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
user openvpn
group openvpn
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device.
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
client
dev tun
proto udp
remote REDACTED 1194
resolv-retry infinite
nobind
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name raspberrypi_0fd30448-bae4-4a6f-8d6f-797f491f8222 name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
::::    Recursive list of files in       ::::
::: /etc/openvpn/easy-rsa/pki shows below :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
dh2048.pem
extensions.temp
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
openssl-easyrsa.cnf
OpenVPN-MotoG6.ovpn
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
OpenVPN-MotoG6.crt
raspberrypi_0fd30448-bae4-4a6f-8d6f-797f491f8222.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
OpenVPN-MotoG6.key
raspberrypi_0fd30448-bae4-4a6f-8d6f-797f491f8222.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 1194/udp
=============================================
::::      Snippet of the server log      ::::
Jan  2 18:17:51 raspberrypi ovpn-server[4778]: Initialization Sequence Completed
Jan  2 18:18:25 raspberrypi ovpn-server[559]: OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Jan  2 18:18:25 raspberrypi ovpn-server[559]: library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Jan  2 18:18:25 raspberrypi ovpn-server[559]: NOTE: your local LAN uses the extremely common subnet address 192.168.0.x or 192.168.1.x.  Be aware that this might create routing conflicts if you connect to the VPN server from public locations such as internet cafes that use the same subnet.
Jan  2 18:18:25 raspberrypi ovpn-server[559]: Diffie-Hellman initialized with 2048 bit key
Jan  2 18:18:25 raspberrypi ovpn-server[559]: Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Jan  2 18:18:25 raspberrypi ovpn-server[559]: Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Jan  2 18:18:25 raspberrypi ovpn-server[559]: TUN/TAP device tun0 opened
Jan  2 18:18:25 raspberrypi ovpn-server[559]: TUN/TAP TX queue length set to 100
Jan  2 18:18:25 raspberrypi ovpn-server[559]: /sbin/ip link set dev tun0 up mtu 1500
Jan  2 18:18:25 raspberrypi ovpn-server[559]: /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Jan  2 18:18:25 raspberrypi ovpn-server[559]: Could not determine IPv4/IPv6 protocol. Using AF_INET
Jan  2 18:18:25 raspberrypi ovpn-server[559]: Socket Buffers: R=[163840->163840] S=[163840->163840]
Jan  2 18:18:25 raspberrypi ovpn-server[559]: UDPv4 link local (bound): [AF_INET][undef]:1194
Jan  2 18:18:25 raspberrypi ovpn-server[559]: UDPv4 link remote: [AF_UNSPEC]
Jan  2 18:18:25 raspberrypi ovpn-server[559]: GID set to openvpn
Jan  2 18:18:25 raspberrypi ovpn-server[559]: UID set to openvpn
Jan  2 18:18:25 raspberrypi ovpn-server[559]: MULTI: multi_init called, r=256 v=256
Jan  2 18:18:25 raspberrypi ovpn-server[559]: IFCONFIG POOL: base=10.8.0.2 size=252, ipv6=0
Jan  2 18:18:25 raspberrypi ovpn-server[559]: Initialization Sequence Completed
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::
pi@raspberrypi:~ $
```

**Comment by orazioedoardo** [comment]
Must be a different problem then, let's test port forwarding:

- Install tcpdump with `sudo apt install tcpdump`
- Sniff the network interface with `sudo tcpdump -i eth0 port 1194`
- Try to connect from your smartphone

You should see some tcpdump output. Specifically the private IP of your Raspberry Pi and the public IP of the device you are trying to connect from. Mask the client IP if you want and post the output (assuming you get any). CTRL-C to stop the packet capture.

**Comment by spectrumcomputing** [comment]
Thanks, I rebooted everything including the router and I'm now connected perfectly. Thank you and Happy 2020!

**Comment by orazioedoardo** [comment]
Excellent! Happy new Year to you too.
